version: '3'
services:
  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"

  backend:
    container_name: node
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: db-gif
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhateste
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql